spring:
  application:
    name: example-rocketmq-consumer
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 47.92.50.126:9876
        bindings:
          input: {consumer.orderly: true}
      bindings:
        input: {destination: test-topic, content-type: text/plain, group: test-group, consumer.maxAttempts: 1}

server:
  port: 9092

management:
  endpoints:
    web:
      exposure:
        include: '*'
