spring:
  application:
    name: example-kafka-consumer
  cloud:
    stream:
      kafka:
        binder:
          brokers: 39.100.31.158:9092
          auto-add-partitions: true
          auto-create-topics: true
      bindings:
        input:
          destination: mytopic
          # 分组，同一 group 下的实例只有一个会去消费消息，避免了多实例重复消费
          group: s1



server:
  port: 9094

management:
  endpoints:
    web:
      exposure:
        include: '*'

